name: first-workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-22.04
    steps: 
      - name: printing hello
        run: echo "hello"
      - name: print multiple line
        run: |
             echo "hello"
             echo "hi"
      
